app:
    resource: "@AppBundle/Controller/"
    type: annotation
    
api:
    resource: "@AppBundle/RestController/"
    prefix: api/
    type: annotation
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"